import { ACTOR_ROLE, type ActorRole } from "./types.js";

export const ACTION = {
  CONTRACTOR_SELF_REGISTER: "CONTRACTOR_SELF_REGISTER",
  CONTRACTOR_MANAGE_OWN_SITE: "CONTRACTOR_MANAGE_OWN_SITE",
  QR_SCAN: "QR_SCAN",
  TEAM_MEMBER_SCAN: "TEAM_MEMBER_SCAN",
  TEAM_MEMBER_MANAGE_SITE: "TEAM_MEMBER_MANAGE_SITE",
  TEAM_MEMBER_VIEW_REWARDS: "TEAM_MEMBER_VIEW_REWARDS",
  CONTRACTOR_VIEW_REWARDS: "CONTRACTOR_VIEW_REWARDS",
  ADMIN_PRINT_QR: "ADMIN_PRINT_QR",
  ADMIN_CANCEL_QR: "ADMIN_CANCEL_QR",
  ADMIN_REVERSE_QR: "ADMIN_REVERSE_QR",
  ADMIN_VIEW_CONTRACTOR: "ADMIN_VIEW_CONTRACTOR",
  ADMIN_REGISTER_CONTRACTOR: "ADMIN_REGISTER_CONTRACTOR",
  ADMIN_EDIT_CONTRACTOR: "ADMIN_EDIT_CONTRACTOR",
  ADMIN_MANAGE_STAFF: "ADMIN_MANAGE_STAFF",
  ADMIN_FULFILL_REWARD: "ADMIN_FULFILL_REWARD",
  ADMIN_MANAGE_REWARD_CATALOG: "ADMIN_MANAGE_REWARD_CATALOG",
  ADMIN_MANAGE_PROMOTIONS: "ADMIN_MANAGE_PROMOTIONS",
  ADMIN_VIEW_ITEM_CODES: "ADMIN_VIEW_ITEM_CODES",
  ADMIN_MANAGE_ITEM_CODES: "ADMIN_MANAGE_ITEM_CODES",
  PROMOTION_VIEW: "PROMOTION_VIEW",
  REPORT_EXPORT: "REPORT_EXPORT",
  REPORT_VIEW: "REPORT_VIEW",
} as const;

export type Action = (typeof ACTION)[keyof typeof ACTION];

const permissions: Record<ActorRole, ReadonlySet<Action>> = {
  [ACTOR_ROLE.CONTRACTOR]: new Set([
    ACTION.CONTRACTOR_MANAGE_OWN_SITE,
    ACTION.QR_SCAN,
    ACTION.CONTRACTOR_VIEW_REWARDS,
    ACTION.PROMOTION_VIEW,
  ]),
  [ACTOR_ROLE.TEAM_MEMBER]: new Set([
    ACTION.QR_SCAN,
    ACTION.TEAM_MEMBER_SCAN,
    ACTION.PROMOTION_VIEW,
  ]),
  [ACTOR_ROLE.OWNER]: new Set([
    ACTION.ADMIN_PRINT_QR,
    ACTION.ADMIN_CANCEL_QR,
    ACTION.ADMIN_REVERSE_QR,
    ACTION.ADMIN_VIEW_CONTRACTOR,
    ACTION.ADMIN_REGISTER_CONTRACTOR,
    ACTION.ADMIN_EDIT_CONTRACTOR,
    ACTION.ADMIN_MANAGE_STAFF,
    ACTION.ADMIN_FULFILL_REWARD,
    ACTION.ADMIN_MANAGE_REWARD_CATALOG,
    ACTION.ADMIN_MANAGE_PROMOTIONS,
    ACTION.ADMIN_VIEW_ITEM_CODES,
    ACTION.ADMIN_MANAGE_ITEM_CODES,
    ACTION.REPORT_EXPORT,
    ACTION.REPORT_VIEW,
  ]),
  [ACTOR_ROLE.STAFF]: new Set([
    ACTION.ADMIN_PRINT_QR,
    ACTION.ADMIN_CANCEL_QR,
    ACTION.ADMIN_REVERSE_QR,
    ACTION.ADMIN_VIEW_CONTRACTOR,
    ACTION.ADMIN_VIEW_ITEM_CODES,
    ACTION.REPORT_VIEW,
  ]),
  [ACTOR_ROLE.SYSTEM]: new Set([]),
};

export function can(actorRole: ActorRole, action: Action): boolean {
  return permissions[actorRole].has(action);
}
